apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yf-client
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cyator/yf-config.git
    targetRevision: HEAD
    path: k8s/client
  destination:
    server: https://kubernetes.default.svc
    namespace: yf
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
