apiVersion: apps/v1
kind: Deployment
metadata:
  name: yf-server-deployment
  labels:
    app: yf-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yf-server
  template:
    metadata:
      labels:
        app: yf-server
    spec:
      containers:
        - name: yf-server
          image: cyator/yotefresh-server:0.0.0
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: yf-server-configmap
            - secretRef:
                name: yf-server-secret
